apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: hello-cron
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      completions: 4
      template:
        spec:
          containers:
            - name: hello-cron-job
              image: busybox
              args:
                - /bin/sh 
                - -c 
                - date ; echo Hello from kubernetes cluster 
          restartPolicy: Never             

