
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: dobby-rs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dobby-pod
  template:
    metadata:
      labels:
        app: dobby-pod
    spec:
      containers:
        - name: dobby
          image: thecasualcoder/dobby
          ports:
            - containerPort: 4444
          readinessProbe:
            httpGet:
              path: /readiness
              port: 4444
            initialDelaySeconds: 20
            periodSeconds: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 4444
            initialDelaySeconds: 20
            periodSeconds: 3


---

apiVersion: v1
kind: Service
metadata:
  name: dobby-svc-np
spec:
  type: NodePort
  selector:
      app: dobby-pod
  ports:
  - protocol: TCP
    port: 4444
    targetPort: 4444
    nodePort: 30003