apiVersion: v1
kind: Pod
metadata: 
  name: meta-config-pod
spec:
  containers:
    - name: meta-config
      image: sunitparekh/metadata:v2.0
      env:
        - name: MONGODB_URI
          valueFrom:
            configMapKeyRef:
              name: meta-config
              key: mongo_url



# kubectl apply -f metaservice-configmap.yaml
# kubectl get cm 
# kubectl apply -f meta-pod-fromConfig.yaml  
# kubectl exec meta-config-pod -it --sh 
#   $env

              