apiVersion: apps/v1
kind: ReplicaSet
metadata:
 name: metadata-rs
spec:
 replicas: 2
 selector:
  matchLabels:
   app: metadata-pod
 template:
  metadata: 
   labels:
    app: metadata-pod   
  spec:
   containers:
    - name: exercise2
      image: sunitparekh/metadata:v1.0
      livenessProbe:
        httpGet:
          path: actuator/health
          port: 8080
        initialDelaySeconds : 10
        periodSeconds: 1
 
