apiVersion: v1
kind: Pod
metadata:
 name: exercise-metadata
 labels:
   app: metadata
spec:
 containers:
  - name: exercise-service
    image: sunitparekh/metadata:v1.0
    ports:
      - containerPort: 8080


---

apiVersion: v1
kind: Service
metadata:
 name: metadata-service
spec:
  type: NodePort
  selector:
      app: metadata
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30003