apiVersion: v1
kind: Pod
metadata:
  name: empty-dir
spec:
  volumes:
    - name: html
      emptyDir: {}
  containers:
    - name: c1
      image: nginx
      ports:
        - containerPort: 80
      volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
    - name: c2
      image: debian
      volumeMounts:
        - name: html
          mountPath: /html
      command: ["/bin/sh", "-c"]
      args:
        - while true; do
          date >> /html/index.html;
          sleep 5;
          done



# $ kubectl create -f empty-dir.yaml

# # create 2 verticle split pane for showcase 2 container commands side by side

# $ kubectl exec empty-dir -c c1 -it -- bash
# $ mount | grep html
# $ tail -f /usr/share/nginx/html/index.html

# $ kubectl exec empty-dir -c c2 -it -- bash
# $ mount | grep html
# $ tail -f /html/index.html

# $ kubectl delete pod empty-dir

# # apply again to showcase all data gone after restart
# $ kubectl create -f empty-dir.yaml
# $ kubectl exec empty-dir -c c1 -it -- bash
# $ tail -f /usr/share/nginx/html/index.html          