apiVersion: v1
kind: Pod
metadata:
  name: host-path
spec:
  volumes:
    - name: html
      hostPath:
        path: /test/nginx/html
        type: Directory
  containers:
    - name: c1
      image: nginx
      ports:
        - containerPort: 80
      volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
    - name: c2
      image: debian
      volumeMounts:
        - name: html
          mountPath: /html
      command: ["/bin/sh", "-c"]
      args:
        - while true; do
          date >> /html/index.html;
          sleep 5;
          done


# $ kubectl create -f host-path.yaml
# $ kubectl describe pod host-path
# # notice failture as the directory on host machine does not exists

# $ kubectl delete pod host-path

# # create directly on node

# $ kubectl create -f host-path.yaml
# $ kubectl describe pod host-path

# # on host machine
# $ cd /home/vagrant/nginx/html
# $ tail -f index.html


# # delete and recreate pod to be lucky on same machine
# $ kubectl delete pod host-path
# $ kubectl apply -f host-path.yaml          